language: scala
scala:
   - 2.11.6
   - 2.10.4

env:
  - STRIPSXMLPATH="./flaming-tyrion/lexicon/data/" data="1.0-6.22.15-1"
install: ./install.sh
script: "sbt clean coverage test"
after_success: "sbt coveralls"
